apiVersion: v1
kind: Service
metadata:
  name: note-manager-service
spec:
  type: NodePort
  selector:
    app: note-manager-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080
