apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "production"
  DB_PORT: "3306"
  DB_HOST: "note-manager-db-service"
  LOG_LEVEL: "info"
  DB_CONNECTION_LIMIT: "10"
  DB_QUEUE_LIMIT: "0"