apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: note-manager-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: note-manager.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: note-manager-service
            port:
              number: 3000