apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-manager-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-manager-app
  template:
    metadata:
      labels:
        app: note-manager-app
    spec:
      containers:
      - name: note-manager-app
        image: note-manager-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "note-manager-db-service"
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "mydb"
