apiVersion: apps/v1
kind: Deployment
metadata:
  name: note-manager-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: note-manager-db
  template:
    metadata:
      labels:
        app: note-manager-db
    spec:
      containers:
      - name: note-manager-db
        image: note-manager-db:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"
        - name: MYSQL_DATABASE
          value: "mydb"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "password"
