---
# Network Policy app
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: note-manager-app-netpol
spec:
  podSelector:
    matchLabels:
      app: note-manager-app
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {} 
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: note-manager-db
    ports:
    - protocol: TCP
      port: 3306
      # allow dns requests
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53

---
# Network Policy db
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: note-manager-db-netpol
spec:
  podSelector:
    matchLabels:
      app: note-manager-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: note-manager-app
    ports:
    - protocol: TCP
      port: 3306